set1 = set([1, 2, 3, 4, 5, 6])
set2 = set([7, 8, 9, 0, 1, 2])

print(set1.isdisjoint(set2))
print(set1.issuperset(set2))
print(set1.issubset(set2))
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.symmetric_difference(set2))
set1.update(set2)
print(set1)
set1.intersection_update(set2)
print(set1)
set1.symmetric_difference_update(set1)
print(set1)
set1.discard(1)
print(set1)
print(set1.pop())
